### ISSUE TITLE
Unlicense?

### ISSUE THREAD

**Issue by Hexstream** [chee/kdlcl#1]
You seem a bit undecided about the license. I had never heard of MIT-0 before...

I strongly recommend [the Unlicense](https://unlicense.org/), which I have been using for [all my open-source projects](https://www.hexstreamsoft.com/) (except [one](https://www.hexstreamsoft.com/libraries/clhs/)) for more than a decade. One advantage is that the Unlicense is much more popular than MIT-0. (**Fun fact:** the Unlicense is listed as a choice in the shortlist of recommended licenses when you create a new repo on GitHub!)

For your consideration. :)

**Comment by chee** [comment]
Oh hey, it's Jean-Philippe Paradis!

Thanks! I normally release all my code under GPL-3.0-or-later. But all my other creative works are CC0, so I went shopping around for a license that's like that, but for software.

I did take a look at the Unlicense, which does take care of the public-domainification part, but it doesn't have the escape hatch feature for jurisdictions without a public domain (or where dedicating to the public domain is impossible). 

The OSI does not recommend using the CC0 for software, so I figured I'd try to find something that grants unlimited, unrestricted access under copyright law. That's how I ended up with MIT-0, which is the MIT license sans its single condition.

What I really want is `(if public-domain-p unlicense mit-0)`.

**Comment by chee** [comment]
> but it doesn't have the escape hatch feature for jurisdictions without a public domain 

Oh, I guess I am completely wrong here and the Unlicense is in fact exactly what I want. OK, I'll update that now.

**Comment by chee** [comment]
OK, well I've just spent 1 hour reading software licenses and I feel less informed than I did before I started.

> In jurisdictions that recognize copyright laws, the author or authors of this software dedicate any and all copyright interest in the software to the public domain.

This part seems confusing to me because Germany _does_ recognize copyright law, but does not allow you to dedicate things to the public domain. I think this is functionally equivalent to the clause not being there at all?

Anyway, I'm very confused and also hungry so I'll use the Unlicense for now. I may revisit later.

**Comment by Hexstream** [comment]
Awesome!! 🎉

[The Unlicense](https://unlicense.org/) seems pretty straightforward to me, basically it says:

1. In jurisdictions where we can dedicate this software to the public domain, we do (¶ 1 & 3);
2. You can do anything whatsoever with this software (¶ 2);
3. You can't sue us if anything goes wrong with this software (¶ 4).

The most important part for most users is point 2 (which always applies), and point 1 is a nice bonus, where applicable. Point 3 is to protect the provider.

**Comment by chee** [comment]
> 1. In jurisdictions where we can dedicate this software to the public domain, we do (¶ 1 & 3);

That's the thing, though! It doesn't say that in ¶3! It says "in jurisdictions that recognize copyright laws", which is not the same as the jurisdictions that allow someone to dedicate their work to the public domain! For instance in Germany, which recognizes copyright law but where you cannot place something in the public domain.
In addition "public domain" means different things in different jurisdictions. For instance, I understand that in France the author and original title of a work must be cited even if it is in the public domain. What is the effect of the Unlicense in France?

The CC0 does a great job of this, by preserving the public domain dedication to the "maximum extent permitted" under the law, and licensing everything else without limit or condition. What I really want is a version of CC0 where the patent limitation has been replaced with an explicit patent grant. Know any good lawyers?

**Comment by Hexstream** [comment]
Perhaps the wording could be tweaked a little bit one day, but it probably doesn't matter if the public domain dedication part of the license inherently or accidentally fails in some jurisdictions, as the unconditional blanket grant of rights cited in the second paragraph should cover all use-cases anyway.

**Comment by chee** [comment]
> Perhaps the wording could be tweaked a little bit one day, but it probably doesn't matter if the public domain dedication part of the license inherently or accidentally fails in some jurisdictions, as the unconditional blanket grant of rights cited in the second paragraph should cover all use-cases anyway.

I agree it should. But I don't like that there is a bunch of text there that doesn't seem to be doing anything? It doesn't seem to have been written with an understanding of the laws it's trying to apply. 

MIT-0 is good because it's short and precise containing only language that's already been cleared by countless legal departments. It just removes the clause that tells you what you can't do.

I think the fact it's universal language that applies the same to everyone with no ifs or buts is a point in its favour. In fact I've been won over by my own argument here and I'm going to switch back to MIT-0.

Thank you for this interesting discussion, and for taking a look at my repository.

**Comment by Hexstream** [comment]
![:shrug:](https://global.hexstream.dev/non-free/images/pinkie-shrug.png)
